apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      env: production-webapp
  template:
    metadata:
      name: webapp-pod
      labels:
        env: production-webapp
    spec:
      containers:
      - name: webapp
        image: no1pelz/bastion_webapp_v2:latest
